// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function FireErrorEvent(arg1:number,arg2:string):Promise<void>;

export function FireEvent(arg1:number,arg2:string):Promise<void>;

export function GenerateSitemap(arg1:models.SitemapConfig):Promise<void>;

export function GetConfig():Promise<models.Config>;

export function GetSitemapConfig():Promise<models.SitemapConfig>;

export function OpenDirectoryDialog():Promise<string>;

export function SetConfig(arg1:string,arg2:models.Config):Promise<void>;
