// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FireErrorEvent(arg1, arg2) {
  return window['go']['main']['App']['FireErrorEvent'](arg1, arg2);
}

export function FireEvent(arg1, arg2) {
  return window['go']['main']['App']['FireEvent'](arg1, arg2);
}

export function GenerateSitemap(arg1) {
  return window['go']['main']['App']['GenerateSitemap'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RunLoop() {
  return window['go']['main']['App']['RunLoop']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}
