// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConfig():Promise<models.Config>;

export function OpenDirectoryDialog():Promise<string>;

export function RunLoop():Promise<void>;

export function SetConfig(arg1:string,arg2:models.Config):Promise<void>;
